# Generated by Django 4.2.30 on 2026-07-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_team_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='appid',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Appid'),
        ),
        migrations.AddField(
            model_name='user',
            name='openid',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Openid'),
        ),
    ]
